### ISSUE TITLE
Overridden in a stronger layer (Root Layer)

### ISSUE THREAD

**Issue by Siwakonrome** [NVIDIA-Omniverse/kit-extension-sample-defectsgen#5]
2023-12-26 08:02:12  [Warning] [omni.kit.widget.layers.layer_model] /Replicator/Cube_Xform.xformOp:rotateXYZ is overridden in a stronger layer (Root Layer).
When I was click review defect.

**Comment by jaeyeun1** [comment]
try using the newest version of Code, which is 2023.1.1
I had the same error and was struggling for hours to fix it and then it just magically disappeared when I ran the extension with the newest version of Code.

**Comment by Siwakonrome** [comment]
Thank you.

**Comment by Siwakonrome** [comment]
Issue is resolved
